### ISSUE TITLE
Need more info on these lines

### ISSUE THREAD

**Issue by ashishsantikari** [rahul-thakoor/air-pi-play#2]
https://github.com/rahul-thakoor/air-pi-play/blob/75e31b63debc3b5ef3791320563ad48119094f1b/docker-compose.yml#L9-L10

I would like to know what are these lines about

**Comment by rahul-thakoor** [comment]
This maps the devices from the host into the running container. It is technically not required here since we are using a privileged container but i would like to make the container not privileged and add required capabilities for rpiplay to run as a stretch goal.

You can read more [here](https://www.balena.io/docs/learn/develop/hardware/) and [here](https://docs.docker.com/engine/reference/commandline/run/#add-host-device-to-container---device)
